---
# install nginx
- name: "Installer nginx  ::: {{ipv4_address}}"
  ansible.builtin.apt:
    update_cache: true
    name: nginx
    state: present
- name: Activer et Démarrer nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Vérifier que nginx répond
  ansible.builtin.uri:
    url: http://localhost:80
    status_code: [200]
  register: this
     
- name: Afficher le résultat
  ansible.builtin.debug:
    msg: "Nginx répond avec le code == {{this.status}}"